grafana:
  enabled: true
  adminUser: admin
  adminPassword: sre-capstone-admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    retention: 2d
    scrapeInterval: 15s

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
