apiVersion: v1
kind: Service
metadata:
  name: shop-sre-api
  namespace: sre-prr
  labels:
    app: shop-sre-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: shop-sre-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
